# Generated by Django 4.2.20 on 2025-04-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catefory',
            new_name='Category',
        ),
    ]
